# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-19 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='user_id',
            new_name='user',
        ),
    ]
