# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-24 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20180823_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='product',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='goods',
            field=models.ManyToManyField(to='App.Goods'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
